
package org.example.jaxws.server_topdown;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "org.example.PersonService", targetNamespace = "http://example.org/", wsdlLocation = "file:/Users/hitit/sem6/RSI/3-Kapala-Michal/src/main/resources/personservice.wsdl")
public class OrgExamplePersonService
    extends Service
{

    private final static URL ORGEXAMPLEPERSONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORGEXAMPLEPERSONSERVICE_EXCEPTION;
    private final static QName ORGEXAMPLEPERSONSERVICE_QNAME = new QName("http://example.org/", "org.example.PersonService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/hitit/sem6/RSI/3-Kapala-Michal/src/main/resources/personservice.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORGEXAMPLEPERSONSERVICE_WSDL_LOCATION = url;
        ORGEXAMPLEPERSONSERVICE_EXCEPTION = e;
    }

    public OrgExamplePersonService() {
        super(__getWsdlLocation(), ORGEXAMPLEPERSONSERVICE_QNAME);
    }

    public OrgExamplePersonService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORGEXAMPLEPERSONSERVICE_QNAME, features);
    }

    public OrgExamplePersonService(URL wsdlLocation) {
        super(wsdlLocation, ORGEXAMPLEPERSONSERVICE_QNAME);
    }

    public OrgExamplePersonService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORGEXAMPLEPERSONSERVICE_QNAME, features);
    }

    public OrgExamplePersonService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrgExamplePersonService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServiceImplPort")
    public PersonService getPersonServiceImplPort() {
        return super.getPort(new QName("http://example.org/", "PersonServiceImplPort"), PersonService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServiceImplPort")
    public PersonService getPersonServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.org/", "PersonServiceImplPort"), PersonService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORGEXAMPLEPERSONSERVICE_EXCEPTION!= null) {
            throw ORGEXAMPLEPERSONSERVICE_EXCEPTION;
        }
        return ORGEXAMPLEPERSONSERVICE_WSDL_LOCATION;
    }

}
